require:
  - rubocop-performance
  - './.rubocop/cops.rb'
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'reference/**/*'

Style/StringLiterals:
  EnforcedStyle: "double_quotes"

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Performance/MethodObjectAsBlock:
  Enabled: false # I like em 🤷

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*' # no idea why rubocop-rspec/config/default.yml isnt excluding these

Layout/LineLength:  # Changed from Metrics/LineLength
  Max: 160

Performance/ChainArrayAllocation:
  Enabled: false # caution to the wind

Style/Documentation:
  Enabled: false 

Metrics/ModuleLength:
  Exclude:
    - 'spec/support/fixtures.rb'

Style/EndlessMethodComment:
  Enabled: true

Style/EndlessMethod:
  EnforcedStyle: allow_always
